pymmcore-plus/pymmcore-widgets

.github/workflows/ci.yml, tox.ini
=> test: Fix github tests

src/pymmcore_widgets/__init__.py, src/pymmcore_widgets/_slider_dialog_widget.py, tests/test_slider_dialog_widget.py
This PR adds the Slider Dialog widget and the tests.
=> feat: add Slider Dialog widget

src/pymmcore_widgets/__init__.py, src/pymmcore_widgets/_objective_widget.py, src/pymmcore_widgets/_util.py, tests/test_objective_widget.py
This PR adds the Objectives widget and the tests.
=> feat: add Objectives widget

.github/workflows/cron.yml
See: https://github.com/ianhi/pymmcore-widgets/actions/runs/2671576282
Closes: #35 
Closes: #36 
Closes: #37
=> fix: fix pre-tests

src/pymmcore_widgets/__init__.py, src/pymmcore_widgets/_core.py, src/pymmcore_widgets/_load_system_cfg_widget.py, tests/test_load_system_cfg_widget.py
This PR adds the widget to load the micromanager system cfg and the tests.
=> feat: add Load System cfg widget

.pre-commit-config.yaml, pyproject.toml, src/pymmcore_widgets/_device_widget.py
=> chore: Update precommit

.github/workflows/ci.yml, .github/workflows/cron.yml, pyproject.toml
=> fix: add vispy to pyproject.toml test

.github/workflows/ci.yml, .github/workflows/cron.yml, pyproject.toml
fix `pre-test` and set `pyside6` version to 6.3.2 because of a bug in the new 6.4.0 version
closes #59
=> test: Fix pre-test

examples/channel_widget.py, examples/configuration_widget.py, examples/default_camera_exposure_widget.py, examples/device_widget.py, examples/exposure_widget.py, examples/group_preset_widget.py, examples/image_widget.py, examples/live_button.py, examples/objectives_widget.py, examples/presets_widget.py, examples/property_browser_widget.py, examples/property_widget.py, examples/slider_dialog_widget.py, examples/snap_button.py, examples/stage_widget.py, examples/state_device_widget.py, pyproject.toml
This PR adds simple examples for all the widgets.
=> docs: Add Examples

.github/workflows/ci.yml
reverts the change to tests that pinned the micromanager devices
=> test: unpin mm device version

README.md, src/pymmcore_widgets/_exposure_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_first_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_preset_widget.py, src/pymmcore_widgets/_pixel_size_widget.py, src/pymmcore_widgets/_property_browser.py, src/pymmcore_widgets/_property_widget.py, src/pymmcore_widgets/_slider_dialog_widget.py, src/pymmcore_widgets/_util.py, tests/test_exposure_widget.py, tests/test_prop_widget.py
This PR renames all the `CMMCorePlus` widgets arguments as `mmcore`.
=> fix: core -> mmcore

.github/workflows/ci.yml, src/pymmcore_widgets/_image_widget.py, tests/test_image_preview.py
i think i got it @fdrgsp!  by adding parent to SceneCanvas
=> test: fix windows segfaults on image test

src/pymmcore_widgets/_mda/_channel_table_widget.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_sample_explorer_widget.py, tests/test_channel_table_widget.py
as mentioned in https://github.com/pymmcore-plus/pymmcore-widgets/pull/129#issuecomment-1476384266 this PR adds a warning icon to the right of the `Advanced QCheckBox` that is shown only if the `Advanced QCheckBox` is **not** checked and some of the `Advanced` values are not their default values.
___
=> feat: add channel advanced warning icon

src/pymmcore_widgets/_shutter_widget.py, tests/test_shutter_widget.py
This PR update the `ShutterWidget` because of the new changes in the `pymmcore-plus` `snapImage` method: https://github.com/pymmcore-plus/pymmcore-plus/pull/197.
Related to closed PR https://github.com/pymmcore-plus/pymmcore-widgets/pull/144#issuecomment-1595219347.
=> fix: update ShutterWidget for new snapImage signals + tests

src/pymmcore_widgets/_mda/_general_mda_widgets.py, src/pymmcore_widgets/_mda/_mda_widget.py
make `SaveLoadSequenceWidget` private -> `_SaveLoadSequenceWidget`
=> refactor: make SaveLoadSequenceWidget private

src/pymmcore_widgets/_mda/_channel_table_widget.py, src/pymmcore_widgets/_mda/_general_mda_widgets.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_time_plan_widget.py, src/pymmcore_widgets/_util.py, tests/test_channel_table_widget.py, tests/test_mda_widget.py
This is the first of a few PRs I'll be doing to clean up the MDAWidget a bit.
I think I'm going to standardize on using useq objects (instead of dictionaries) internally.  It makes for much cleaner typing internally
=> refactor: use useq.Channel objects in `ChannelTable`

src/pymmcore_widgets/_mda/_zstack_widget.py
like #170  and #171 , for Zstack, returning useq objects
=> refactor: return useq object from stack_widget.value()

src/pymmcore_widgets/_mda/_grid_widget.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_positions_table_widget.py, src/pymmcore_widgets/_util.py, tests/test_grid_widget.py
partner to #170, this uses useq-schema objects for the grid widget (rather than dicts/strings)
=> refactor: use useq-schema objects for GridWidget

src/pymmcore_widgets/_property_widget.py
=> fix: catch errors when updating property browser values from core

pyproject.toml, src/pymmcore_widgets/_mda/_grid_widget.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_positions_table_widget.py, src/pymmcore_widgets/_util.py, tests/test_grid_widget.py, tests/test_position_table_widget.py
mostly just bumps to useq 0.4.1
=> build: updates for fov_size in useq 0.4, bump pymmcore-plus

src/pymmcore_widgets/useq_widgets/_positions.py
add `minimum` and `maximum` parameters to the `FloatColumn`.
=> fix: increase FloatColumn min/max in Position table

examples/mda_widget2.py
=> fix: fix new mdaexample without channels

src/pymmcore_widgets/_stage_widget.py, tests/test_stage_widget.py
closes #240 
@dpshepherd, after this, it would be:
```python
wdg = StageWidget('deviceLabel', step=1)
wdg.setStep(...)
```
=> feat: add step() and setStep() methods to StageWidget

src/pymmcore_widgets/useq_widgets/_column_info.py, tests/test_useq_widgets.py
=> fix: fix quantity edit

.github/workflows/cron.yml, src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/useq_widgets/_positions.py, tests/test_core_state.py, tests/test_useq_core_widgets.py
This PR  adds/fixes few things that I found out while using one of  Nikon Ti2-E about the `Autofocus` behavior in the `MDAWidget` and in the `CoreConnectedPositionTable`.
=> feat: update Autofocus related methods, warn when 'Set AF Offset per Position' checked but autofocus not engaged

.pre-commit-config.yaml, pyproject.toml, src/pymmcore_widgets/_objectives_pixel_configuration_widget.py, src/pymmcore_widgets/hcwizard/_dev_setup_dialog.py, src/pymmcore_widgets/useq_widgets/_z.py, tests/conftest.py
amazing ruff did it again and can now replace black
=> chore: use ruff-format instead of black

src/pymmcore_widgets/useq_widgets/_grid.py
the grid widget is the main thing keeping the height of the MDAWidget too big... this puts it into a QScrollArea and sets a small size hint to encourage scrolling
=> fix: make grid widget scrollable

src/pymmcore_widgets/useq_widgets/_mda_sequence.py
some axes were getting left out
=> fix: fix selection of axis orders in mdaWidget.setValue

pyproject.toml, src/pymmcore_widgets/_util.py
fixes #300, requires https://github.com/pymmcore-plus/pymmcore-plus/pull/357
=> fix: fix blocker

src/pymmcore_widgets/hcwizard/_peripheral_setup_dialog.py, src/pymmcore_widgets/hcwizard/devices_page.py, tests/test_stack_viewer.py
this PR just adds a Select All checkbox when picking the children of a Hub device that you want to configure
=> feat: add select all for hub devices

src/pymmcore_widgets/_pixel_configuration_widget.py
Thanks to @tlambert03 for the suggestion!
Here's what it looks like on Windows 11, and it also looks good on WSL - can someone else confirm this looks good to them?
=> style: Manually compute sizeHint()

examples/stage_widget.py, src/pymmcore_widgets/_stage_widget.py, tests/test_stage_widget.py
closes #331 
edit:   let's do #332 elsewhere
=> refactor: refactor stage widget

pyproject.toml
just releasing now, so may fail at first
=> build: pin useq-schema to 0.5.0

.pre-commit-config.yaml, examples/install_widget.py, pyproject.toml, src/pymmcore_widgets/_install_widget.py, tests/test_install_widget.py
updates install widget to include device interface version, and ability to set active install:
=> feat: updates to install widget

.github/workflows/ci.yml, .github/workflows/docs.yml, README.md, docs/_gen_widget_pages.py, pyproject.toml, uv.lock
=> build: setup uv dependency groups and use for testing

examples/stage_explorer_widget.py, src/pymmcore_widgets/control/_stage_explorer/_stage_explorer.py, src/pymmcore_widgets/control/_stage_explorer/_stage_position_marker.py, src/pymmcore_widgets/control/_stage_explorer/_stage_viewer.py, tests/test_stage_explorer.py
small aesthetic changes, adding the option for grid lines, and a coordinate overlay on mouse over
https://github.com/user-attachments/assets/26d07919-f783-4c02-981b-542b91cf44f4
=> feat: grid lines and hover position in stage explorer

src/pymmcore_widgets/device_properties/_property_widget.py, uv.lock
small fix required for pymmcore-plus 0.15
=> fix: fix property widget for pymmcore-plus 0.15.0

src/pymmcore_widgets/device_properties/_property_widget.py
=> fix: fix prop widgets with no range

tests/test_image_preview.py
Sorry @tlambert03, I forgot to push the tests I wrote on #475.
=> test: add test for ImagePreview
