pymmcore-plus/pymmcore-widgets

src/pymmcore_widgets/_snap_button_widget.py, tests/test_snap_button_widget.py
This PR removes `QPushButton` style arguments form  the `__init__` method and update the test.
=> remove style args from SNAP button __init__  + update test

src/pymmcore_widgets/_presets_widget.py
Fix poor width rendering of preset widgets as shown in https://github.com/pymmcore-plus/napari-micromanager/issues/184.
fixes https://github.com/pymmcore-plus/napari-micromanager/issues/184.
=> fix: fix _set_combo_view method

src/pymmcore_widgets/_channel_widget.py, src/pymmcore_widgets/_core.py, src/pymmcore_widgets/_device_widget.py, src/pymmcore_widgets/_exposure_widget.py, src/pymmcore_widgets/_group_preset_table_widget.py, src/pymmcore_widgets/_live_button_widget.py, src/pymmcore_widgets/_load_system_cfg_widget.py, src/pymmcore_widgets/_objective_widget.py, src/pymmcore_widgets/_presets_widget.py, src/pymmcore_widgets/_property_browser.py, src/pymmcore_widgets/_property_widget.py, src/pymmcore_widgets/_slider_dialog_widget.py, src/pymmcore_widgets/_snap_button_widget.py, src/pymmcore_widgets/_stage_widget.py, tests/conftest.py, tests/test_combo_message_box_widget.py, tests/test_device_widget.py, tests/test_presets_widget.py, tests/test_property_browser.py
This PR removes the `get_core_singleton()` method from all the widgets and replaces it with `CMMCorePlus.instance()` method.
=> Fix: Remove 'get_core_singleton()' and replace with CMMCorePlus.instance()

src/pymmcore_widgets/_live_button_widget.py, src/pymmcore_widgets/_snap_button_widget.py
both the snap and live buttons have a bug where the internal state (`self._camera`) can go stale if the user uses `setCameraDevice`.  This PR removes the internal pointer to the device label, and always uses the core as the source of truth.
in general, I guess this is  reminder that we should, whenever possible, avoiding saving _any_ state on these widgets that has the potential to go out of sync with core (unless we _must_ save it for some reason)
=> fix: fix state error in snap and live buttons

src/pymmcore_widgets/_live_button_widget.py, tests/test_live_button.py
This PR removes style `args` in the `__init__` method for the `live button` and sets them as `properties` + tests update.
=> fix: move LIVE button __init__ args to properties + update test

examples/group_preset_widget.py, pyproject.toml, src/pymmcore_widgets/__init__.py, src/pymmcore_widgets/_channel_widget.py, src/pymmcore_widgets/_group_preset_table_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_first_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_group_preset_table_widget.py, src/pymmcore_widgets/_presets_widget.py, src/pymmcore_widgets/_property_browser.py, src/pymmcore_widgets/_util.py, tests/test_channel_widget.py, tests/test_group_preset_widget.py, tests/test_presets_widget.py
This PR add the ability to create, delete or modify `groups` and `presets` directly from the `GroupPresetTableWidget`.
Uses the new sets of `pymmcore-plus` signals and methods from https://github.com/pymmcore-plus/pymmcore-plus/pull/139. 
*** to do: update pymmcore-plus pyproject.toml when https://github.com/pymmcore-plus/pymmcore-plus/pull/139 is merged.
=> feat: update GroupPresetTableWidget + PresetsWidget + tests

src/pymmcore_widgets/_objective_widget.py
This PR fixes an issue happening if there is no `FocusDevice` in the micromanager cfg.
Currently, the objective widget is using the `_ObjectiveStateWidget` subclass (objective moving up/down when changed) of the `StateDeviceWidget` class and it works well only if there is a `FocusDevice`. It will raise `RuntimeError: No device with label ""` if there is no `FocusDevice`.
=> fix: use standard StateDeviceWidget if no FocusDevice

pyproject.toml, src/pymmcore_widgets/_image_widget.py, src/pymmcore_widgets/_live_button_widget.py, src/pymmcore_widgets/_shutter_widget.py, tests/test_live_button.py, tests/test_shutter_widget.py, tests/test_snap_button_widget.py
This PR replaces the old sequence acquisition signals names. To be merged **AFTER** https://github.com/pymmcore-plus/pymmcore-plus/pull/163.
=> fix: fix sequence acquisition signal names

src/pymmcore_widgets/_camera_roi_widget.py, src/pymmcore_widgets/_exposure_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_first_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_group_preset_table_widget.py, src/pymmcore_widgets/_mda_widget/_grid_widget.py, src/pymmcore_widgets/_mda_widget/_mda_gui.py, src/pymmcore_widgets/_mda_widget/_mda_widget.py, src/pymmcore_widgets/_pixel_size_widget.py, src/pymmcore_widgets/_presets_widget.py, src/pymmcore_widgets/_sample_explorer_widget/_sample_explorer_gui.py, src/pymmcore_widgets/_sample_explorer_widget/_sample_explorer_widget.py, src/pymmcore_widgets/_shutter_widget.py, src/pymmcore_widgets/_snap_button_widget.py, tests/test_group_preset_widget.py
This fixes a lot more Qt namespaces.
@fdrgsp  ... the longer story here is that Qt has moved away from putting all Enums of a given class at the top level, and now requires the full namespace.  For example, rather than `QSizePolicy.Fixed`, it should be `QSizePolicy.Policy.Fixed` ... and so on.  They've supported the new full namespace since about 5.12 (and deprecated the top level access back then as well)... and are finally removing them, which is why you saw that PySide6 error.
so we should just always prefer the full name
=> refactor: correct many Qt namespaces

.github/workflows/docs.yml, mkdocs.yml, pyproject.toml
this will deploy docs to gh-pages on push to main, and test it on any pull-request
=> ci: add ci to build docs

src/pymmcore_widgets/_general_mda_widgets.py, src/pymmcore_widgets/_mda_widget/_mda_gui.py, src/pymmcore_widgets/_mda_widget/_mda_widget.py, src/pymmcore_widgets/_sample_explorer_widget/_sample_explorer_gui.py, src/pymmcore_widgets/_sample_explorer_widget/_sample_explorer_widget.py, tests/test_mda_widget.py, tests/test_sample_explorer_widget.py
This PR removes duplicated code between mda and sample explorer.
It creates single widgets for channels, z-stacks, time and positions.
Closes #76
=> feat: General Widgets for MDAs

src/pymmcore_widgets/_mda_widget/_mda_gui.py, src/pymmcore_widgets/_sample_explorer_widget/_sample_explorer_gui.py, src/pymmcore_widgets/_zstack_widget.py
minor fix. This PR unckeck the z-stack `QGroupWidget` checkbox at startup.
=> fix: disable z checkbox at startup

tests/test_mda_widget.py
small change to make sure qtbot cleans up a lingering widget after a test
=> test: cleanup grid widget after test

src/pymmcore_widgets/_camera_roi_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_group_widget.py, src/pymmcore_widgets/_mda_widget/_mda_widget.py, src/pymmcore_widgets/_property_browser.py, src/pymmcore_widgets/_sample_explorer_widget/_sample_explorer_widget.py, tests/conftest.py, tests/test_camera_roi_widget.py, tests/test_group_preset_widget.py, tests/test_mda_widget.py, tests/test_shutter_widget.py, tests/test_table_pixel_size_widget.py
This PR adds a new fixture in conftest that is automatically used (with [autouse](https://docs.pytest.org/en/6.2.x/fixture.html#autouse-fixtures-fixtures-you-don-t-have-to-request)) that asserts that no top level widgets are remaining after the test closes.  It enforces good widget "hygiene", to make sure that we're not leaking references.
One thing I found while doing it is that the fixture pattern of 
```python
@pytest.fixture
def some_widget(qtbot):
my_widget = Widget()
qtbot.addWidget(my_widget)
return my_widget
```
actually prevents good widget cleanup.  so those have been removed when found
=> test: fix and assert widget cleanup

src/pymmcore_widgets/__init__.py, src/pymmcore_widgets/_property_widget.py
adds `connectCore` and `disconnectCore` methods to `PropertyWidget` that enables/disables changes in the widget to update the core
=> feat: allow propertywidget to disconnect from core

src/pymmcore_widgets/_device_property_table.py
This PR changes the blue color of the properties icons since it is not very visible when in dark mode. It is now gray and it seems to look good in both light and dark mode. 
---
=> fix: change property browser icons color to gray

src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_sample_explorer_widget.py, tests/test_sample_explorer_widget.py
This pulls the `_create_row_cols_overlap_group` off the SampleExplorer in favor of a new class.  As I was doing that, I noticed that there's also already a very similar `GridWidget` in `_mda._grid_widget`.  So in a follow up PR we should be figuring out how to deduplicate those two and only have one of them
=> refactor: make _GridParams class for _create_row_cols_overlap_group

src/pymmcore_widgets/_mda/_sample_explorer_widget.py
cc @fdrgsp 
using `useq.Position` was a good way to get around the typing issues in SampleExlorer (the `tuple[str, float, float, float] | tuple[str, float, float]` issue)... particularly since that was the ultimate desired output type anyway.
An alternative would have also been to use a `typing.NamedTuple`, which would let you have an optional fourth "z" parameter (so you don't need to deal with the 3-tuple or 4-tuple everywhere)
=> fix: fix typing in sample explorer

src/pymmcore_widgets/_mda/_mda_widget.py
The MDA `run_button` is not showing when `_include_run_button` is `True`. By mistake this has been changed and this PR fixes it.
=> fix: fix MDA run_button not showing when _include_run_button=True

examples/time_plan_widget.py, examples/z_stack_widget.py, src/pymmcore_widgets/__init__.py
This PR adds `ZStackWidget` and `TimePlanWidget` to the docs and also adds examples.
=> docs: add time and z plan widgets to docs

src/pymmcore_widgets/_channel_widget.py, src/pymmcore_widgets/_shutter_widget.py, src/pymmcore_widgets/_snap_button_widget.py, tests/test_channel_widget.py, tests/test_shutter_widget.py
The shutter widget should not be so eagerly modifying shutter state. It was closing all shutters it interacted with on initialization and also interfering with autoshutter behavior by closing all shutters after snapping an image. This is best left to control by the core AutoShutter mechanism. Particularly a problem as for some scopes the BF light source is defined as shutter device, so the widget was turning off a halogen lamp which could never warm up in time for a fast exposure.
This was causing a bug for @JasonYu1 and me where all our BF images had no signal. Some test code demonstrating this:
```python
import numpy as np
from pymmcore_plus import CMMCorePlus, DeviceType
from pymmcore_widgets import ShuttersWidget
from qtpy.QtWidgets import QApplication
app = QApplication([])
core = …
```
=> fix: Stop shutter widget from accidentally closing shutter

src/pymmcore_widgets/_mda/_channel_table_widget.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_time_plan_widget.py, tests/test_channel_table_widget.py, tests/test_mda_widget.py, tests/test_sample_explorer_widget.py
This PR adds the possibility (enabled through a `QCheckBox`) to set the `z_offset`, `do_stack` and `acquire_every` options to every channel in the `ChannelTable`.
---
=> feat: add "advanced" channel options to ChannelTable

src/pymmcore_widgets/_stage_widget.py
This PR adds the `AutoRepeat` function to the to `StageWidget` `QPushButtons` so that you can keep the buttons pressed to move the stages.
=> feat: add AutoRepeat to stage buttons

src/pymmcore_widgets/_presets_widget.py
This PR fixes an issue in the `PresetsWidget` that raises a `ValueError`.
Example:
With the current version, running the following code will generate a `ValueError`
```py
from pymmcore_widgets import PresetsWidget
from pymmcore_plus import CMMCorePlus
mmc = CMMCorePlus.instance()
mmc.loadSystemConfiguration()
p = PresetsWidget("Channel")
mmc.loadSystemConfiguration()
```
```
ValueError                                Traceback (most recent call last)
File ~/Library/CloudStorage/Dropbox/git/pymmcore-widgets/src/pymmcore_widgets/_presets_widget.py:155, in PresetsWidget._on_property_changed(self, device, property, value)
153     if (device, "State") not in self.dev_prop:
154         return
--> 155 self._set_style_if_props_not_match_preset()
File …
```
=> fix: minor fix in PresetsWidget

pyproject.toml, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_time_plan_widget.py, src/pymmcore_widgets/_util.py, tests/test_mda_widget.py, tests/test_sample_explorer_widget.py, tests/test_time_table.py
This PR adds to the `TimePlanWidget` the possibility to set `useq-schema` `MultiPhaseTimePlan`.
---
=> feat: add phases to TimePlanWidget

src/pymmcore_widgets/_group_preset_widget/_group_preset_table_widget.py, tests/test_group_preset_widget.py
Remove redundant `removeRow(row)` in `_delete_group` and `_delete_preset` methods and only calling `_mmc.deleteConfigGroup(group)` is sufficient.
=> fix: remove redundant 'removeRow(row)' 

src/pymmcore_widgets/_mda/_time_plan_widget.py
Fixing the `_create_new_row` method in `TimePlanWidget` so that we can pass `0.0` as a possible `interval`: adding `if isinstance(interval, timedelta)` instead of only `if interval`.
=> fix: minor time widget fix

tests/test_core_state.py, tests/test_mda_widget.py
closes #122
It's possible we're missing some deeper property that gets changed in core, but this PR at leasts makes a place to add those tests
=> test: add test for core state modification

src/pymmcore_widgets/_mda/_mda_widget.py
This fixes the bug that lead to #158. 
this was causing the calc time function to be called before subclasses finished their `init` which could lead to errors. It's also not obvious that we need to call this every time the config is reloaded.
I also removed the setting of the channel group as I'm pretty sure that that does not belong this deep in a widget, and it also seems to violate the spirit of https://github.com/pymmcore-plus/pymmcore-widgets/issues/122. But @fdrgsp I would really appreciate you taking a look to make sure I'm not messing up something else somewhere by removing that.
=> fix: don't calculate time before subclasses have been inited

src/pymmcore_widgets/_mda/_channel_table_widget.py, src/pymmcore_widgets/_mda/_grid_widget.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_positions_table_widget.py, src/pymmcore_widgets/_mda/_time_plan_widget.py, src/pymmcore_widgets/_mda/_zstack_widget.py, tests/test_mda_widget.py
This brings significant speed ups (e.g. 1 min -> 7 seconds) to the mda widget and some of it's subcomponents. The most significant thing I was running into as a user was that we were having the UI freeze as we tried to type out larger numbers for timepoints. This even resulted in us having to close everything and restart at least once. This was caused by slowness in the min total time calculation, and it being called over and over as we typed into the spinbox.
=> perf: Improve speed of mda widget

src/pymmcore_widgets/_mda/_general_mda_widgets.py, src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/_mda/_time_plan_widget.py, src/pymmcore_widgets/_util.py, tests/test_mda_widget.py
This PR removes the time estimating functionality from the MDAWidget.  After #157, it became clear that that was a major slowdown.  
https://github.com/pymmcore-plus/useq-schema/pull/117 adds a mechanism to estimate the time of an experiment that is many orders of magnitude faster than the present approach.  Since it will have effectively no overlap with the current code, this PR just deletes that code, and a followup will replace it
=> refactor: remove time estimates from MDAWidget

src/pymmcore_widgets/_load_system_cfg_widget.py
This PR removes the `QGroupbox` from the `ConfigurationWidget` so that most basic widget are the same (clean and simple). If a `QGroupbox` is needed, the can be added where the widget is used.
note: napari-micromanager are failing because of this line: https://github.com/pymmcore-plus/napari-micromanager/blob/6abd0f50cf7840b7a08b28bd0ad9a428c484f284/src/napari_micromanager/_gui_objects/_toolbar.py#L143 where we set the `QGroupBox` text. Since there is not a `QGroupBox`, we get the error.
=> fix: remove groupbox from config widget

src/pymmcore_widgets/_load_system_cfg_widget.py
Fix napari-micromanager tests.
@fdrgsp, this is what i meant by https://github.com/pymmcore-plus/pymmcore-widgets/pull/185#issuecomment-1701567129
The upcoming fix in napari-micromanager is fine, but it won't "fix" anyone out there who is using napari-micromanager that might install pymmcore-widgets in the meantime.  The lower level libraries always need to support the current version of the   higher level libraries, or emit a deprecation warning
=> fix: fix napari micro tests

tests/conftest.py
still not sure why windows often leaks the image preview widget.  This relaxes the tests
=> test: fix tests by relaxing windows leak tests

src/pymmcore_widgets/_objective_widget.py
This is related to https://github.com/pymmcore-plus/napari-micromanager/issues/288.
This PR updates the `_create_objective_combo()` method so that the objective combo size is adjusted every time a new config is loaded. It's not a major change but It should fix the issue we have in `napari-micromanager`. 
At the moment, the resizing is performed in `napari-micromanager` and this is not ideal since the combo might be deleted/replaced before the resize method is called (https://github.com/pymmcore-plus/napari-micromanager/blob/fa692dc13785629bd9ba277f5d01de8c4039925a/src/napari_micromanager/_gui_objects/_toolbar.py#L241).
This PR is linked to this `napari-micromanager` one: https://github.com/pymmcore-plus/napari-micromanager/pull/290
=> fix: fix objective widget resizing

src/pymmcore_widgets/_mda/_mda_widget.py, src/pymmcore_widgets/useq_widgets/_mda_sequence.py
this prepares for https://github.com/pymmcore-plus/useq-schema/pull/140, related to https://github.com/pymmcore-plus/useq-schema/issues/137
The point is that we shouldn't assume MDASequence.axis_order is a string... but rather a `Sequence[str]`  (which all strings are as well)
=> fix: treat MDASequence.axis_order as Sequence[str] rather than str

src/pymmcore_widgets/_mda/_checkable_tabwidget_widget.py, tests/test_useq_widgets.py
fixes #205 
@fdrgsp, for some reason the tab_index was not getting calculated correctly in `_on_tab_checkbox_toggled`.  Not quite sure why, it was some kind of race condition, because by the time I go into a debugger, it's fixed itself to the proper value.  I generally dislike using lambdas in connections, which is why I was trying to find the tab from the sender before, so I just simplified the logic there and passed the widget to the callback
=> fix: fix correct index enablement on checkable tab widget

src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/useq_widgets/_column_info.py, src/pymmcore_widgets/useq_widgets/_data_table.py, src/pymmcore_widgets/useq_widgets/_positions.py, tests/test_useq_core_widgets.py
This PR update the functionality of the `CoreConnectedPositionTable`:
- when clicking on the add button, we add the current XY or Z stage coordinates.
- handles the cases where the XY or Z stage are not selected/loaded. If not loaded, the respective table column will be hidden and the `value()` method will output `None` for the x, y, and/or z positions coordinates.
to see this behavior:
```py
from pymmcore_widgets.mda._core_positions import CoreConnectedPositionTable
from pymmcore_plus import CMMCorePlus
import useq
mmc = CMMCorePlus.instance()
mmc.loadSystemConfiguration()
mmc.unloadDevice("Z")
p = CoreConnectedPositionTable()
p.show()
pos = [useq.Position(x=1, y=2, z=3)]
p.setValue(pos)
print(p.value())
>>> (Position(x=1.0, y=2.0, z=None, name=None, sequence=None),)
```
=> fix: update CoreConnectedPositionTable + test

src/pymmcore_widgets/mda/_xy_bounds.py
very strangely, icon translation about its center was working differently on mac and windows.  this fixes it, but we don't know why :)
=> fix: fix icon transform

src/pymmcore_widgets/useq_widgets/_positions.py
Units of the `PositionTable` for the x, y, z coordinates are usually expressed in `µm` (as in useq-schema). This PR remake the table header units from `mm` to `µm`. 
merge after #217
=> fix: units to µm

src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/mda/_core_z.py, tests/test_useq_core_widgets.py
If building an `MDASequence` with a `relative` `z_plan` without a specified `Position`, we need to specify the relative starting position.
=> fix: add position if relative z_plan

examples/mda_useq.py, src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/mda/_core_z.py, src/pymmcore_widgets/useq_widgets/_positions.py, tests/test_useq_core_widgets.py
use the `CoreConnectedGridPlanWidget()` and `CoreConnectedZPlanWidget()` when opening sub-sequence `_MDAPopup` widget.
=> fix: use core connected widgets for core connected  sub-sequence _MDAPopup

src/pymmcore_widgets/useq_widgets/_column_info.py
we need to be able to set the time `interval` in the `TimePlanWidget` to `0` from the GUI.
=> fix: accept 0 as interval

src/pymmcore_widgets/_mda/_checkable_tabwidget_widget.py
noticed when playing with https://github.com/pymmcore-plus/napari-micromanager/pull/292 that isChecked is sometimes failing with checkable tab widget.  this seems to fix it (not entirely sure why)
=> fix: retain pointers in QCheckableTabWidget

src/pymmcore_widgets/_device_property_table.py
If any widget has an exception in the DevicePropertyBrowser, the whole thing fails to load.  This PR catches individual widget errors and logs them.  So at least the whole browser won't crash (that one widget will be unavailable though)
see https://github.com/pymmcore-plus/napari-micromanager/issues/293 for the overflow issue and see #223 for the "actual" fix
=> fix: catch errors in property widget when building device property table

src/pymmcore_widgets/useq_widgets/_positions.py
Since at the moment `useq-schema` does not support setting the `keep_shutter_open_across` property in `Position` sub-sequences, we hide the checkboxes (https://github.com/pymmcore-plus/useq-schema/blob/b0522c48b1fd7acb0904b0c7e54965d3791d2ffe/src/useq/_mda_sequence.py#L250-L253).
closes #227
=> fix: hide shutter open in sub_seq

src/pymmcore_widgets/_device_property_table.py, src/pymmcore_widgets/_device_type_filter.py, src/pymmcore_widgets/_group_preset_widget/_add_group_widget.py, src/pymmcore_widgets/_group_preset_widget/_edit_group_widget.py, src/pymmcore_widgets/_property_browser.py, src/pymmcore_widgets/_property_widget.py, tests/conftest.py, tests/test_prop_widget.py
Pre-init properties must not be set after initialization, and this is now enforced upstream by https://github.com/micro-manager/mmCoreAndDevices/pull/376 
This PR fixes tests here resulting from that change, and makes PropertyWidgets disabled after device initialization
=> fix: disallow setting pre-init props after device initialization

.github/workflows/ci.yml, src/pymmcore_widgets/hcwizard/roles_page.py
fix because of the test not passing  on pyqt6. 
The test fails because the `QCheckBox` `Qt.CheckState` is different in `pyqt6` and `pyside6` compared to `pyqt5` and `pyside2`.
Two possible solutions are:
- using try/except
```py
def _on_auto_shutter_changed(self, state: Qt.CheckState) -> None:
try:
val = "1" if state == Qt.CheckState.Checked.value else "0"
except AttributeError:
val = "1" if state == Qt.CheckState.Checked else "0"
self._model.core_device.set_property(Keyword.CoreAutoShutter, val)
```
- using bool **_(this is the one currently implemented in this PR_**):
```py
def _on_auto_shutter_changed(self, state: int) -> None:
val = "1" if bool(state) else "0"
self._model.core_device.set_property(Keyword.CoreAutoShutter, val)
```
=> fix: fix the test on PyQt6

src/pymmcore_widgets/mda/_xy_bounds.py, src/pymmcore_widgets/useq_widgets/_z.py
fix the style of the ZPlanWidget that is currently not working very well when switching between a light and dark mode.
BEFORE
---
AFTER
---
also removing `L_ARR = "\u2B05"  # LEFTWARDS BLACK ARROW` and using a `MDI6.arrow_left_thick` icon for the `_use_suggested_btn` because on windows it looks quite weird.
BEFORE -> AFTER
=> fix: fix style of ZPlanWidget

tests/test_prop_widget.py
This fixes tests after the release of 11.1.1.71.0, which reverted the strict feature flag added in the previous version (that makes setting pre-init properties after initialization a no-op)
=> test: fix tests for pymmcore 11.1.1.71.0

src/pymmcore_widgets/_group_preset_widget/_group_preset_table_widget.py, tests/test_group_preset_widget.py
When using the `Save cfg` button, if you don't manually add the extension `.cfg` to the filename, it is not automatically added. This PR fixes this issue + adds a test for it.
=> fix: minor fix in save config in GroupPresetTableWidget

src/pymmcore_widgets/useq_widgets/_grid.py, tests/test_useq_widgets.py
The `GridPlanWidget` overlap spinbox value was not correctly expressed in percentage as in `useq-schema`. This PR fixes it + update the tests.
related to (https://github.com/pymmcore-plus/useq-schema/issues/149#issuecomment-1832557352)
@tlambert03 do you want to switch it form 0-100% to 0-1? Should we change it also in `useq-schema`?
=> fix: fix overlap in GridPlanWidget

src/pymmcore_widgets/_stage_widget.py, tests/test_stage_widget.py
This PR adds two checkboxes to the `StageWidget`, `invert X` and `invert Y`, to invert the direction of the stage movements when the arrow buttons are pressed.
=> feat: add the possibility to invert the axis in the stage widget

src/pymmcore_widgets/_stage_widget.py, tests/test_stage_widget.py
This PR add a fix to PR #260. We need to hide the `invert X` and `invert Y` checkboxes if the stage is not a `XYStage` type.
test updated.
=> fix: hide invert xy checkboxes if not xy stage in StageWidget

src/pymmcore_widgets/hcwizard/devices_page.py
The other half of https://github.com/pymmcore-plus/pymmcore-plus/pull/308
this makes sure to call `model.load_available_devices()` after successfully initializing a hub device in the ConfigWizard.  (and https://github.com/pymmcore-plus/pymmcore-plus/pull/308 makes sure to call `getInstalledDevices()`)
=> fix: fix missing hub peripherals in config wizard

src/pymmcore_widgets/mda/_core_channels.py, src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/useq_widgets/_channels.py, tests/test_useq_core_widgets.py, tests/test_useq_widgets.py
This PR fix two bugs in the `ChannelTable` and create a `CoreConnectedChannelTable` to handle any changes when using a core.
1) the `_group_combo` is "hidden" if there is only one channel group but if you use the `setChannelGroups` method and you set more than one group, the `_group_combo` does not show up. This PR fixes this behavior.
2) before,  we did not get the channel group **from the `_group_combo`** and when adding a channel using the table button, the channel group was set to the default "Channel" even if the channel group selected in the `_group_combo` had a different name (we did not see that before because in the test config the channel group is named "Channel" as the default). This PR fixes this behavior by adding a `_on_rows_inserted` method connected to the table …
=> fix: fix bugs in  ChannelTable

src/pymmcore_widgets/_image_widget.py, tests/test_stage_widget.py
this PR would allow https://github.com/pymmcore-plus/pymmcore-plus/pull/314 to pass downstream tests.
This relaxes the expectations of the `imageSnapped` signal coming from pymmcore-plus.  It no longer requires the callback to provide an argument, instead opting to call `getImage` manually after receiving the signal.  see details in PR above, but ultimately that allows pymmcore-plus to emit signals in a slightly less surprising way and is probably better in the long term.
=> refactor: relax expectations of imageSnapped callback

src/pymmcore_widgets/mda/_core_mda.py, tests/test_useq_core_widgets.py
fixes a threading issue with mda running (and logging) after test has finished
=> test: fix test logging warning

docs/_gen_widget_pages.py
@tlambert03 this fixes the fact that the png of some widgets in the docs are not correct. We just needed to exclude `QMenu` together with  `QFrame` objects.
=> fix: fix docs not grabbing widget png correctly

docs/_gen_widget_pages.py, docs/_hooks.py, docs/getting_started.md, docs/index.md, docs/widgets/index.md, mkdocs.yml, pyproject.toml, src/pymmcore_widgets/_camera_roi_widget.py, src/pymmcore_widgets/_channel_widget.py, src/pymmcore_widgets/_exposure_widget.py, src/pymmcore_widgets/_install_widget.py, src/pymmcore_widgets/_live_button_widget.py, src/pymmcore_widgets/_snap_button_widget.py, src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/useq_widgets/_mda_sequence.py
- fixes a bunch of broken links that were showing up in the build logs
- fixes #253 
- adjust widget links to link to top of page
- pulls out widget list from overview page to widgets/index
=> docs: bunch of documentations fixes

src/pymmcore_widgets/_image_widget.py, tests/test_image_preview.py
Necessary after https://github.com/pymmcore-plus/pymmcore-plus/pull/314
When a MDA is running, we should be able to choose whether the ImagePreview  widget should update or not.
=> fix: choose to update ImagePreview when mda is running

examples/mda_demo.py, examples/mda_sequence_widget.py, examples/mda_widget.py
this renames `examples/mda_widget` to `examples/mda_demo` (since it's a relatively more complicated example), and creates a simpler mda_widget to show in the docs
=> docs: rename mda_widget to mda_demo

src/pymmcore_widgets/_channel_group_widget.py
use `textActivated` instead of `currentTextChanged` for the `QComboBox` connection.
fixes https://github.com/pymmcore-plus/pymmcore-widgets/issues/289.
=> fix: fix issue with channel group widget not working with only one group

src/pymmcore_widgets/hcwizard/intro_page.py, src/pymmcore_widgets/hcwizard/roles_page.py, tests/test_config_wizard.py
the state of the core devices loaded before opening a config wizard was leaking into the output
=> fix: fix bug in config wizard where core state bleeds into model

src/pymmcore_widgets/useq_widgets/points_plans/_random_points_widget.py, tests/useq_widgets/test_useq_points_plans.py
@tlambert03 what do you think about adding the `allow_overlap` option as a checkbox? I think it can be a useful one to have...
in this PR:
- add allow_overlap checkbox
- add order combobox
=> feat: add overlap checkbox

src/pymmcore_widgets/useq_widgets/_well_plate_widget.py, tests/useq_widgets/test_plate_widget.py
currently if we create the `WellPlateWidget` without passing a `plate` arg, the plate is not drawn even if there is a plate selected in the combobox. This will fix that.
=> fix: WellPlateWidget initial drawing

src/pymmcore_widgets/_group_preset_widget/_edit_group_widget.py, tests/test_group_preset_widget.py
This PR makes the group name editable when interacting with the edit group dialog in the `GroupPresetTableWidget`.
closes #324
=> fix: make name editable EditGroupWidget

src/pymmcore_widgets/_pixel_configuration_widget.py
=> style: fix pixel affine table

src/pymmcore_widgets/useq_widgets/_mda_sequence.py
I believe that these alterations make it clearer that the buttons save and load MDA parameters, and not images/devices/etc.
I do wonder if the text is a little wide though, what do others think?
Closes #335
=> style: clarify save/load buttons in MDAWidget

src/pymmcore_widgets/useq_widgets/_grid.py
This PR, closing #339, adds a `HACK` to prevent the OS accent color from filling up the `GridPlanWidget`'s radio buttons on Windows 11. This `HACK` seems to be the least-bad of the different options that could resolve the issue, which are:
* Setting the style sheet, as I did here, to override the accent color fill
* Adding the radio buttons to the layout of the `QScrollArea` itself, which is worse as it alters the hierarchy of the widget.
@tlambert03 and/or @fdrgsp: I'd be happy for your opinions and/or testing. It looks nice to me on Windows 11, and on WSL (Wayland)
=> style: unfill radio buttions in GridPlanWidget

src/pymmcore_widgets/mda/_xy_bounds.py
I believe that the behavior I described in #337 was a simple misordering of the `_PositionSpinBox`es. I reordered them and things seem to work as described!
Closes #337
=> fix: Align spin boxes and labels in GridPlan

src/pymmcore_widgets/useq_widgets/_mda_sequence.py
This PR avoids exceptions arising from the attempt to save/load MDA settings from YAML files, when pyyaml is not installed.
Notably, I made the decision to prevent the selection of a YAML file within the `QFileDialog`. We could have alternatively shown it, but prevented the exception (through a `try`/`except` or other means) instead. I prefer this method as it leaves no room for unexpected behavior (namely a user trying to save into a YAML file and then save not being completed).
Closes #333
=> fix: Only allow YAML save/load when YAML available

src/pymmcore_widgets/_group_preset_widget/_group_preset_table_widget.py
In this PR we enable the columns resizing of the `GroupPresetTableWidget`.
https://github.com/user-attachments/assets/606266dd-f916-46ef-878a-929a66d17d19
closes #323
=> fix: update the GroupPresetTableWidget policy

src/pymmcore_widgets/mda/_core_mda.py
Just a first thought potentially for viewer integration etc. Would give a little more fine-grained control when customizing/subclassing the MDAWidget.
=> refactor: split run mda in mda widget

src/pymmcore_widgets/_property_widget.py, tests/test_prop_widget.py
wasn't getting emitted properly
=> fix: fix valueChanged signals on PropertyWidget

src/pymmcore_widgets/mda/_core_grid.py, src/pymmcore_widgets/useq_widgets/_grid.py
This PR provides a different approach to constructing a Grid for an MDA sequence by refactoring the `GridPlanWidget`. It's a draft PR because the code is messy, and because I want feedback. It's perfectly fine if others prefer the existing `GridPlanWidget` and we discard these changes.
From UX testing with a collaborator, we filed issues such as #342 and #339, and the general impression that I got was that the `GridPlanWidget` could be slimmed down. I was thinking about the following goals when I constructed this new design:
* Shorten the `GridPlanWidget` so that it is more likely the full widget will fit within the `MDAWidget`, without a scroll bar.
* Shorten the distance between the "bottom stuff" (`Order`, `Overlap`, and `Relative To`) and the grid construction parameters being used. …
=> feat: Refactor GridPlanWidget

examples/grid_plan_widget.py, src/pymmcore_widgets/mda/_core_grid.py, src/pymmcore_widgets/useq_widgets/_grid.py, src/pymmcore_widgets/useq_widgets/_mda_sequence.py
taking advantage of @gselzer 's work in #351 to clean up the GridPlan Widget a bit more, removing conditionals and putting them on the stack widget classes
=> refactor: more grid plan cleanup

src/pymmcore_widgets/hcwizard/config_wizard.py, tests/test_config_wizard.py
Often, I've found myself accidentally launching the Hardware Configuration Wizard. When I cancel (`reject`) the wizard, my configuration is unloaded. See gselzer/pymmcore-plus-sandbox#29 for more discussion.
This PR remedies the situation by reloading the last used configuration on rejection.
=> feat: reload prior config file on HCW rejection

src/pymmcore_widgets/mda/_core_positions.py, tests/test_useq_core_widgets.py
@tlambert03 I removed this in #362 but it was a mistake. AF per position should be disabled when using HCS since it is not in the WellPlatePlan model.
=> fix: disable Autofocus checkbox when using HCSWizard

src/pymmcore_widgets/_group_preset_widget/_add_first_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_add_preset_widget.py, src/pymmcore_widgets/_group_preset_widget/_cfg_table.py, src/pymmcore_widgets/_group_preset_widget/_edit_preset_widget.py
fixes #363
This is just a patch for the immediate issue, these widgets still contain a lot of duplicated code and possible bugs, and should be replaced (with one of #307, #320, #338, etc...)
=> fix: fix splitting logic and deduplicate code in Groups Presets Widgets

.github/workflows/ci.yml, .github/workflows/cron.yml, README.md, docs/getting_started.md, pyproject.toml, src/pymmcore_widgets/_util.py, src/pymmcore_widgets/config_presets/_group_preset_widget/_cfg_table.py, src/pymmcore_widgets/config_presets/_pixel_configuration_widget.py, src/pymmcore_widgets/device_properties/_device_property_table.py, src/pymmcore_widgets/device_properties/_properties_widget.py, src/pymmcore_widgets/hcs/_plate_calibration_widget.py, src/pymmcore_widgets/hcs/_util.py, src/pymmcore_widgets/hcs/_well_calibration_widget.py, src/pymmcore_widgets/hcwizard/_dev_setup_dialog.py, src/pymmcore_widgets/hcwizard/_peripheral_setup_dialog.py, src/pymmcore_widgets/hcwizard/_simple_prop_table.py, src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/useq_widgets/_channels.py, src/pymmcore_widgets/useq_widgets/_column_info.py, src/pymmcore_widgets/useq_widgets/_data_table.py, src/pymmcore_widgets/useq_widgets/_mda_sequence.py, src/pymmcore_widgets/useq_widgets/_positions.py, src/pymmcore_widgets/useq_widgets/_well_plate_widget.py, src/pymmcore_widgets/useq_widgets/points_plans/_grid_row_column_widget.py, src/pymmcore_widgets/useq_widgets/points_plans/_random_points_widget.py, src/pymmcore_widgets/views/_stack_viewer/_stack_viewer.py, tests/test_presets_widget.py, tests/test_stack_viewer.py
this also pins pyside6 to 6.7.3 ... still quite hard to find a good match there
this also stops testing the experimental stack viewer on PySide2/6, since those tests fail too often, and we'll likely move to ndv
=> build: drop support for python 3.8, test 3.12

src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/useq_widgets/_positions.py, tests/useq_widgets/test_useq_widgets.py
fixes #380 
for now, this will set the "include z" checkbox to True if _any_ of the positions have a Z position.   If only some of them have a z position, it will emit a warning.
If we need the feature in the future, we could further elaborate to somehow let some rows have a Z position of None while others don't
=> fix: fix include_z when setting stage positions value in PositionTable widget

src/pymmcore_widgets/useq_widgets/_z.py
fix for #376: set the minimum possible range for the RANGE_AROUND mode to 0 so we do not have negative values.
closes #376
=> fix: "range" in range-around z-stack widget starts form 0 (no negative numbers)

src/pymmcore_widgets/device_properties/_device_property_table.py
tests failing because of https://github.com/hgrecco/pint/issues/2074.
update for #375 .
@tlambert03 instead of using a specific icon as you mentioned in #375 , what about changing the background color as we do for the read only props?
closes #375
=> feat: indicate pre-init properties in device property browser

src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/useq_widgets/_mda_sequence.py, tests/useq_widgets/test_useq_widgets.py
tests failing because of https://github.com/hgrecco/pint/issues/2074.
fix the bug in #373.
@tlambert03 the error in #373 is due to the validation of the `useq.schema` [here](https://github.com/pymmcore-plus/useq-schema/blob/6dc031498f62c0d8853ada40188567f6d542335c/src/useq/_mda_sequence.py#L395-L402).  Basically we cannot use the hardware autofocus plan if an absolute z plan (top-bottom) is selected.
to fix that, I've created a method that disables the autofocus checkboxes (and thus remove the autofocus plan to avoid the validation error) if an absolute z plan is selected. If any other z plans (or None) are selected, the autofocus checkboxes are re-enabled. Do you agree with this solution?
closes #373
=> fix: fix z plan and hardware autofocus plan validation error

src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/mda/_core_positions.py, tests/test_useq_core_widgets.py
I found a bug in the `CoreConnectedPositionTable` `_update_autofocus_enablement` method when core `propertyChanged` is called.
to reproduce:
- check the `CoreConnectedPositionTable.af_per_position` checkbox (the AF column will be visible).
- set the `Core Autofocus` to `""`.
- the `CoreConnectedPositionTable.af_per_position` is now disabled but the AF column is still visible.
I fixed this and modified the test so this bug is exposed without this fix.
=> fix: fix af per pos bug on prop changed

src/pymmcore_widgets/mda/_core_z.py, src/pymmcore_widgets/useq_widgets/_z.py, tests/useq_widgets/test_useq_widgets.py
Use radio button in the z plan widget (as in the grid plan widget)
@tlambert03 what do you think?
---
with this PR:
before:
=> feat: use QRadioButtons to select z_plan

examples/mda_widget.py, src/pymmcore_widgets/mda/_core_mda.py, src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/useq_widgets/_mda_sequence.py, src/pymmcore_widgets/useq_widgets/_positions.py, tests/test_useq_core_widgets.py
This PR updates the logic for when the autofocus devices (**Autofocus Axis widget** and **Autofocus Per Position checkbox**)should be disabled to then emit a correct `useq.MDASequence`. 
On top of disabling them when an absolute z plan is selected, this PR adds:
- If no Autofocus device is loaded they are disabled (thus responding to the core `systemConfigurationLoaded` signal).
- They are also disabled if the core `AutoFocus` property is set to `None` (thus responding to the core `propertyChnaged` signal).
=> fix: disable autofocus axis widget if no autofocus device is loaded/selected

src/pymmcore_widgets/useq_widgets/_column_info.py
The Maximum value set in the IntColumn dataclass dictates the maximum number of loops that can be entered into the MDAWidget's  TimePlanWidget.
Requesting to bump the value from the current 10_000 to 99_999 
```python
@dataclass(frozen=True)
class IntColumn(_RangeColumn):
data_type: WdgGetSet = TableIntWidget
minimum: int = 0
maximum: int = 99_999 #was 10_000
```
=> Fix: Bump default maximum for IntColumn from 10_000 to 99_999

src/pymmcore_widgets/mda/_core_grid.py, src/pymmcore_widgets/mda/_xy_bounds.py, src/pymmcore_widgets/useq_widgets/_grid.py, tests/test_useq_core_widgets.py
Not sure if this is the best fix but...
To reproduce the current bug:
```py
from pymmcore_plus import CMMCorePlus
from pymmcore_widgets.mda._core_grid import CoreConnectedGridPlanWidget
mmc = CMMCorePlus()
mmc.loadSystemConfiguration()
g = CoreConnectedGridPlanWidget()
g.show()
g.setMode("bounds")
```
Now manually modify any of the `top/bottom/left/right` values and then run:
```py
g.value()
```
In the current version the `top/bottom/left/right` values are always `0`.
I'm not sure how to test this because if we setup the widget `top/bottom/left/right` values  with the `setValue()` method and then we call the `value()` the `top/bottom/left/right` values  are correct. The difference is that graphically on the widget we do not see the `top/bottom/left/right` values added through the …
=> fix: fix a bug in the CoreConnectedGridPlanWidget when selecting the bound mode

src/pymmcore_widgets/hcs/_plate_calibration_widget.py, src/pymmcore_widgets/mda/_core_positions.py, src/pymmcore_widgets/useq_widgets/_well_plate_widget.py, tests/hcs/test_well_plate_calibration_widget.py
I found two bugs in the `PlateCalibrationWidget` of the `HCSWizard`:
- The `y` positions stored in each `HoverEllipse` item should be negative since we use a coordinate system where y is positive upwards and negative downwards. This PR inverts the sign.
---
- It also fixes the slow behavior that I found when adding position from the HCSWidget (the `_on_rows_inserted` was unnecessarily called every time a row was added)
=> fix: fix plate calibration

src/pymmcore_widgets/config_presets/_pixel_configuration_widget.py, src/pymmcore_widgets/useq_widgets/_column_info.py
This PR increases the decimals in the `pixel value [µm]` column of the `PixelConfigurationWidget` since is currently limited to 2 decimals.
=> feat: add 3 decimals to pixel size config widget 

src/pymmcore_widgets/config_presets/_group_preset_widget/_group_preset_table_widget.py
slight change to layout of groups presets table.  to minimize horizontal:
(before)
=> refactor: 2-row button layout in GroupPresetTableWidget

examples/stage_explorer_widget.py, pyproject.toml, src/pymmcore_widgets/control/_stage_explorer/_stage_explorer.py, src/pymmcore_widgets/control/_stage_explorer/_stage_position_marker.py, src/pymmcore_widgets/control/_stage_explorer/auto_zoom_to_fit_icon.svg, tests/test_stage_explorer.py
Third part of the stage explore widget (#400 ) after #420.
Here we add a stage marker to track the position of the microscope stage.  
TODO:
=> feat: stage explorer part 3

.pre-commit-config.yaml, examples/stage_explorer_widget.py, pyproject.toml, src/pymmcore_widgets/control/_q_stage_controller.py, src/pymmcore_widgets/control/_stage_explorer/_stage_explorer.py, src/pymmcore_widgets/control/_stage_widget.py, tests/test_stage_widget.py
This is an attempt to fix #410 ... it's still a WIP, but it introduces a `_ValueBatcher` object, a generic object that knows how to get/set and add values, and check device busy state.  It manages repeated calls to `add_relative` and/or `set_absolute`, and, maintains an internal awareness of whether we're "done" or not.
That all sounds rather abstract, and it is, but the goal is to have one object that we can *share* (across, say, the stage controller widget, and the stage explorer widget #400 ... that coordinates all of the attempts to control and move the stage, and, importantly, lets them all know when the job is done so they can, for example, snap an image.
The value batcher itself doesn't manage an event loop, and could be moved into pymmcore-plus.  It is wrapped here with a small …
=> fix: Stage controller objects that batch repeated relative/absolute calls and emit moveFinished when done

src/pymmcore_widgets/control/_presets_widget.py, tests/test_presets_widget.py
Yesterday in the lab we accidentally ran into #372, which motivated me to fix the bug. I did see #307, however apparently that PR does not fix the problem.
This PR overrides the `wheelEvent` method to ignore `QWheelEvent`s on preset combo boxes, and adds a test ensuring as such.
=> fix: Disable preset combo scroll

src/pymmcore_widgets/_util.py, src/pymmcore_widgets/config_presets/_group_preset_widget/_group_preset_table_widget.py, src/pymmcore_widgets/control/_presets_widget.py, src/pymmcore_widgets/device_properties/_device_property_table.py, tests/test_presets_widget.py, tests/test_utils.py
Following up on #432, @tlambert03 mentioned that what would be better than just ignoring scroll events would be to redirect them to the parent, since usually users want to scroll the table and not the contents. This PR uses an event filter to do just that.
Unfortunately, the sliders are still tricky, and I had to access the private `_slider` attribute of the `SliderProxy` to get it to work (as @tlambert03 foreshadowed in #432). This PR could be easily cleaned up and merged as is, but I'd prefer to spur discussion on how we make those pesky sliders behave.
Oh, and I need to fix the test I wrote for #432.
closes https://github.com/pymmcore-plus/pymmcore-widgets/issues/372
=> fix: Use an event filter to avoid scrolling

src/pymmcore_widgets/mda/_core_positions.py, tests/test_useq_core_widgets.py
We currently make the position table non-modifiable when we add the position list using the `HCSWIdget`. However, we do not disable the checkboxes. Since removing a position (unchecking the checkbox) would modify the `WellPlatePlan`, we should disable the checkboxes as well.
=> fix: make position checkboxes uncheckable when using HCSWidget

examples/config_groups_tree.py, src/pymmcore_widgets/__init__.py, src/pymmcore_widgets/config_presets/__init__.py, src/pymmcore_widgets/config_presets/_qmodel/_property_setting_delegate.py, src/pymmcore_widgets/config_presets/_views/_config_groups_tree.py, src/pymmcore_widgets/config_presets/_views/_property_setting_delegate.py, tests/test_config_groups_widgets.py
adds just a simple ConfigGroupsTree view, pulled out from #446
=> feat: add ConfigGroupsTree

src/pymmcore_widgets/control/_q_stage_controller.py, tests/_utils.py, tests/conftest.py, tests/test_image_preview.py, tests/test_live_button.py, tests/test_shutter_widget.py, tests/test_snap_button_widget.py
closes #454
looks like there are specifically some things in pytestqt's qtbot.waitSignal that are interacting poorly with the new signals.  This fixes the tests, and allows them to work for pyside6.9 again.  It doesn't preclude the possibility that the new signals have some additional "gotchas" that we need to look out for still.  but does allow us to "unskip" again in pymmcore-plus here: https://github.com/pymmcore-plus/pymmcore-plus/blob/692c2e0e2aedfeaeaf7339f8ff72b86d4811dc86/src/pymmcore_plus/core/_mmcore_plus.py#L2545-L2549
=> fix: fix pyside6 tests

src/pymmcore_widgets/control/_q_stage_controller.py, tests/test_misc.py
related to https://github.com/pymmcore-plus/pymmcore-plus/issues/486 and  https://github.com/pymmcore-plus/pymmcore-remote/pull/11 
this is the one place we've found so far that actually checks isinstance instead of a structural check like hasattr, etc...
this one is trivial, and was an overly explicit catch of a possibly null weakref.  This change should allow pymmcore-widgets to be used with pymmcore-remote.  
Test added to prevent regressions.  
cc @gselzer.  let me know if you have a preferred alternative approach
=> fix: don't check isinstance in stage controller

.pre-commit-config.yaml, examples/temp/grid_from_polygon.py, pyproject.toml, src/pymmcore_widgets/_util.py, src/pymmcore_widgets/control/_rois/roi_model.py, src/pymmcore_widgets/useq_widgets/_grid.py, tests/useq_widgets/test_useq_widgets.py
Add `GridFromPolygon` from `useq-schema`.
This PR replace the local `GridFromPolygon` logic and uses the `GridFromPolygon` form uses-schema.
It also updates `MDAWidget` to be able to show (but not really edit) a `GridFromPolygon`.
https://github.com/user-attachments/assets/38699fc6-abd7-45c0-a081-023d8e17e5fb
=> feat: use useq-schema GridFromPolygon

pyproject.toml, src/pymmcore_widgets/config_presets/_objectives_pixel_configuration_widget.py, src/pymmcore_widgets/control/_channel_group_widget.py, src/pymmcore_widgets/control/_presets_widget.py, tests/test_channel_group_widget.py, tests/test_channel_widget.py, tests/test_objective_pixel_config_widget.py, tests/test_presets_widget.py
This PR implements the <no match> logic discussed in #411.
BEFORE
AFTER
closes #411.
=> fix: remove magenta from preset widget and use <no match> key
